function makeResult(rule, status, evidenceLines) {
  return {
    id: rule.id,
    title: rule.title,
    category: rule.category,
    severity: status === 'pass' ? 'pass' : (status === 'manual' ? 'manual' : rule.severity),
    status: status,
    standards: rule.standards,
    remediation: rule.remediation,
    evidence: evidenceLines && evidenceLines.length ? evidenceLines.slice(0, 6).join('\n') : (status === 'pass' ? 'No matching pattern found in configuration — control appears satisfied.' : 'Not present in configuration.')
  };
}

function findLines(text, regex) {
  const lines = text.split(/\r?\n/);
  const out = [];
  for (const l of lines) {
    if (regex.test(l)) out.push(l.trim());
  }
  return out;
}

const ciscoRules = [
  { id: 'FW-ACC-001', category: 'Access Control', title: 'Overly permissive "any-any" permit rule', severity: 'critical', standards: ['CIS Cisco Firewall Benchmark 3.1', 'NIST SP 800-41 §4.3', 'PCI-DSS 1.2.1'], test: function (t) { const m = findLines(t, /permit\s+(ip|tcp|udp)\s+any\s+any/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Replace broad any-any rules with explicit source/destination/service definitions. Default policy should deny all traffic not explicitly permitted.' },
  { id: 'FW-ACC-002', category: 'Access Control', title: 'ACL does not end in explicit deny with logging', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 3.2'], test: function (t) { const m = findLines(t, /deny\s+ip\s+any\s+any\s+log/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Terminate access lists with an explicit "deny ip any any log" so denied traffic is both blocked and logged for visibility.' },
  { id: 'FW-ACC-003', category: 'Access Control', title: 'IP directed-broadcast not disabled', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 2.4', 'NIST SP 800-41 §4.3'], test: function (t) { const m = findLines(t, /ip directed-broadcast/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Ensure "no ip directed-broadcast" on all interfaces to prevent smurf-style amplification attacks.' },
  { id: 'FW-ACC-004', category: 'Access Control', title: 'IP source routing not disabled', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 2.3'], test: function (t) { const m = /no ip source-route/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Configure "no ip source-route" globally to prevent source-routed packets from bypassing security controls.' },
  { id: 'FW-ACC-005', category: 'Access Control', title: 'Proxy ARP not disabled on interfaces', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 2.5'], test: function (t) { const m = /no ip proxy-arp/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Disable proxy ARP ("no ip proxy-arp") on interfaces where it is not explicitly required to reduce spoofing/MITM risk.' },
  { id: 'FW-ACC-006', category: 'Access Control', title: 'ICMP redirects not disabled', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 2.6'], test: function (t) { const m = /no ip redirects/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Disable ICMP redirects ("no ip redirects") on external-facing interfaces to prevent routing-table manipulation.' },
  { id: 'FW-ACC-007', category: 'Access Control', title: 'Rule base — unused/shadowed rules', severity: 'manual', standards: ['CIS Cisco Firewall Benchmark 3.4'], test: function () { return makeResult(this, 'manual', []); }, remediation: 'Review hit counters over a full business cycle and remove rules with zero hits or that are fully shadowed by earlier, broader rules.' },
  { id: 'FW-ADM-001', category: 'Administrative Access', title: 'Telnet enabled for remote management', severity: 'critical', standards: ['CIS Cisco Firewall Benchmark 5.1', 'PCI-DSS 2.3'], test: function (t) { const m = findLines(t, /transport input[^\n]*telnet/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Disable Telnet on all VTY lines and restrict management access to SSH v2 only ("transport input ssh").' },
  { id: 'FW-ADM-002', category: 'Administrative Access', title: 'SSH version 1 permitted', severity: 'high', standards: ['CIS Cisco Firewall Benchmark 5.2', 'NIST SP 800-41 §5.1'], test: function (t) { const m = findLines(t, /ip ssh version 1\b/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Force SSH v2 with "ip ssh version 2"; SSH v1 has known cryptographic weaknesses.' },
  { id: 'FW-ADM-003', category: 'Administrative Access', title: 'AAA authentication not configured', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 5.4', 'NIST SP 800-41 §4.2'], test: function (t) { const m = /aaa new-model/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable centralized AAA ("aaa new-model") with TACACS+/RADIUS rather than relying solely on local accounts.' },
  { id: 'FW-ADM-004', category: 'Administrative Access', title: 'VTY exec-timeout disabled or excessive', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 5.5'], test: function (t) { const m = findLines(t, /exec-timeout\s+0\s+0/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Set a bounded idle timeout (e.g. "exec-timeout 10 0") on all management lines to reduce session-hijack risk.' },
  { id: 'FW-ADM-005', category: 'Administrative Access', title: 'Enable secret not used (plaintext enable password)', severity: 'critical', standards: ['CIS Cisco Firewall Benchmark 1.1', 'PCI-DSS 8.2'], test: function (t) { const hasPlain = findLines(t, /^\s*enable password\s+/i); const hasSecret = /enable secret\s+\d?\s*\S+/i.test(t); if (hasPlain.length && !hasSecret) return makeResult(this, 'fail', hasPlain); return makeResult(this, 'pass'); }, remediation: 'Replace "enable password" with "enable secret" so the privileged-exec password is stored as an MD5/scrypt hash rather than reversible/plaintext.' },
  { id: 'FW-ADM-006', category: 'Administrative Access', title: 'Password encryption service not enabled', severity: 'high', standards: ['CIS Cisco Firewall Benchmark 1.2'], test: function (t) { const m = /service password-encryption/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable "service password-encryption" so locally stored passwords are not visible in plaintext within the running/startup config.' },
  { id: 'FW-ADM-007', category: 'Administrative Access', title: 'HTTP admin server not disabled', severity: 'high', standards: ['CIS Cisco Firewall Benchmark 1.3'], test: function (t) { const m = findLines(t, /^\s*ip http server\b/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Disable the unencrypted HTTP admin server ("no ip http server"); use "ip http secure-server" if a web UI is required.' },
  { id: 'FW-ADM-008', category: 'Administrative Access', title: 'Minimum password length not enforced', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 1.5', 'PCI-DSS 8.2.3'], test: function (t) { const m = findLines(t, /security passwords min-length\s+\d+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Configure "security passwords min-length 14" (or per policy) to enforce a minimum local password length.' },
  { id: 'FW-ADM-009', category: 'Administrative Access', title: 'Failed-login rate limiting not configured', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 1.6', 'PCI-DSS 8.1.6'], test: function (t) { const m = findLines(t, /login block-for\s+\d+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Configure "login block-for <seconds> attempts <n> within <seconds>" to throttle brute-force login attempts.' },
  { id: 'FW-ADM-010', category: 'Administrative Access', title: 'Configuration change logging (archive) not enabled', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 6.4'], test: function (t) { const m = /archive\b[\s\S]{0,80}log config/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable "archive" + "log config" so configuration changes are tracked with the user and timestamp.' },
  { id: 'FW-MON-001', category: 'Logging & Monitoring', title: 'Logging not enabled', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 6.1', 'NIST SP 800-41 §4.5', 'PCI-DSS 10.1'], test: function (t) { const m = /logging enable|logging on/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable logging ("logging enable") and forward events to a centralized syslog server for retention and review.' },
  { id: 'FW-MON-002', category: 'Logging & Monitoring', title: 'No remote syslog server configured', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 6.2', 'PCI-DSS 10.5'], test: function (t) { const m = findLines(t, /logging host\s+\S+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Configure "logging host <syslog-ip>" to forward logs to a centralized, tamper-resistant log collector.' },
  { id: 'FW-MON-003', category: 'Logging & Monitoring', title: 'Logging severity/buffer level not set appropriately', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 6.3'], test: function (t) { const m = findLines(t, /logging (trap|buffered)\s+(informational|debugging|notifications|warnings)/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Set logging trap/buffer level to at least "informational" so security-relevant events are captured.' },
  { id: 'FW-MON-004', category: 'Logging & Monitoring', title: 'NTP authentication not configured', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 4.3'], test: function (t) { const m = /ntp authenticate/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable "ntp authenticate" with a trusted key so time sources cannot be spoofed, protecting log-timestamp integrity.' },
  { id: 'FW-NET-001', category: 'Network Hardening', title: 'SNMP community string uses default value (public/private)', severity: 'critical', standards: ['CIS Cisco Firewall Benchmark 4.1', 'NIST SP 800-41 §4.4'], test: function (t) { const m = findLines(t, /snmp-server community\s+(public|private)\b/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Remove default community strings. Use SNMPv3 with authentication and encryption instead of v1/v2c community strings.' },
  { id: 'FW-NET-002', category: 'Network Hardening', title: 'SNMP v1/v2c in use instead of v3', severity: 'high', standards: ['CIS Cisco Firewall Benchmark 4.2'], test: function (t) { const m = findLines(t, /snmp-server community/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Migrate to "snmp-server group ... v3 priv" with authNoPriv/authPriv rather than community-string based v1/v2c.' },
  { id: 'FW-NET-003', category: 'Network Hardening', title: 'CDP enabled on external-facing interfaces', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 2.2'], test: function (t) { const m = /no cdp run|no cdp enable/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Disable CDP globally ("no cdp run") or per-interface on any interface facing an untrusted network to avoid information disclosure.' },
  { id: 'FW-NET-004', category: 'Network Hardening', title: 'No login/warning banner configured', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 1.4'], test: function (t) { const m = /banner (motd|login|exec)/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Configure a legal warning banner ("banner login") to support unauthorized-access enforcement.' },
  { id: 'FW-NET-005', category: 'Network Hardening', title: 'Unused/legacy small services enabled', severity: 'low', standards: ['CIS Cisco Firewall Benchmark 2.1'], test: function (t) { const m = findLines(t, /service tcp-small-servers|service udp-small-servers|ip finger/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Disable legacy diagnostic services (finger, small servers) that provide no operational value and expand attack surface.' },
  { id: 'FW-NET-006', category: 'Network Hardening', title: 'Routing protocol authentication not configured', severity: 'medium', standards: ['CIS Cisco Firewall Benchmark 3.5', 'NIST SP 800-41 §4.3'], test: function (t) { const runsRouting = /router (ospf|eigrp|bgp)/i.test(t); if (!runsRouting) return makeResult(this, 'manual', []); const hasAuth = /message-digest-key|authentication (message-digest|md5)|neighbor \S+ password/i.test(t); return hasAuth ? makeResult(this, 'pass') : makeResult(this, 'fail', findLines(t, /router (ospf|eigrp|bgp)/i)); }, remediation: 'Enable MD5/keyed-hash authentication on all dynamic routing protocol adjacencies to prevent route injection.' },
  { id: 'FW-NET-007', category: 'Network Hardening', title: 'Weak IKE/IPsec transform (DES/3DES) permitted', severity: 'high', standards: ['CIS Cisco Firewall Benchmark 7.1', 'NIST SP 800-41 §4.6'], test: function (t) { const m = findLines(t, /\b(des|3des)\b/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Retire DES/3DES from ISAKMP/IPsec transform sets; use AES-256 with SHA-256 and DH group 14+.' },
];

const paloaltoRules = [
  { id: 'FW-ACC-001', category: 'Access Control', title: 'Security rule permits any/any/any', severity: 'critical', standards: ['CIS Palo Alto Networks Benchmark 3.1', 'PCI-DSS 1.2.1'], test: function (t) { const m = findLines(t, /set rulebase security rules[^\n]*from any[^\n]*to any[^\n]*action allow/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Scope security rules to specific zones, addresses and applications; avoid "any" on source, destination and application together.' },
  { id: 'FW-ACC-002', category: 'Access Control', title: 'Rule base — unused/disabled rule review', severity: 'manual', standards: ['CIS Palo Alto Networks Benchmark 3.5'], test: function () { return makeResult(this, 'manual', []); }, remediation: 'Review Policy Optimizer for rules with zero hit-count over 90 days and remove or justify their retention.' },
  { id: 'FW-ACC-003', category: 'Access Control', title: 'Security rules missing application-based control (app-default/any)', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 3.2'], test: function (t) { const m = findLines(t, /set rulebase security rules[^\n]*application any/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Replace "application any" with specific App-ID signatures so policy enforcement is application-aware, not just port-based.' },
  { id: 'FW-ACC-004', category: 'Access Control', title: 'Interzone default-deny logging not enabled', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 3.4', 'PCI-DSS 10.1'], test: function (t) { const m = /set rulebase security rules interzone-default log-end yes/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Enable logging on the interzone-default and intrazone-default rules so implicitly denied traffic is still visible.' },
  { id: 'FW-ADM-001', category: 'Administrative Access', title: 'Telnet management service enabled', severity: 'critical', standards: ['CIS Palo Alto Networks Benchmark 1.1', 'PCI-DSS 2.3'], test: function (t) { const m = findLines(t, /set deviceconfig system service disable-telnet no/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Set "disable-telnet yes" and manage the device exclusively over HTTPS/SSH.' },
  { id: 'FW-ADM-002', category: 'Administrative Access', title: 'HTTP (non-TLS) management service enabled', severity: 'high', standards: ['CIS Palo Alto Networks Benchmark 1.2'], test: function (t) { const m = findLines(t, /set deviceconfig system service disable-http no/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Set "disable-http yes" so management UI is only reachable via HTTPS.' },
  { id: 'FW-ADM-003', category: 'Administrative Access', title: 'Password complexity profile not enforced', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 1.4', 'PCI-DSS 8.2'], test: function (t) { const m = /set mgt-config password-complexity/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Configure a minimum-password-complexity profile under "set mgt-config password-complexity" (length, character classes, history).' },
  { id: 'FW-ADM-004', category: 'Administrative Access', title: 'Idle timeout for admin sessions not configured', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 1.5'], test: function (t) { const m = findLines(t, /set deviceconfig system[^\n]*idle-timeout\s+\d+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Set "set deviceconfig system idle-timeout <=15" minutes so idle GUI/CLI sessions are automatically terminated.' },
  { id: 'FW-ADM-005', category: 'Administrative Access', title: 'Login/warning banner not configured', severity: 'low', standards: ['CIS Palo Alto Networks Benchmark 1.6'], test: function (t) { const m = /set deviceconfig system login-banner/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Configure "set deviceconfig system login-banner" with an authorized-use warning banner.' },
  { id: 'FW-ADM-006', category: 'Administrative Access', title: 'Management interface uses default/self-signed certificate', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 1.7'], test: function (t) { const m = /set deviceconfig system ssl-tls-service-profile/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Import a CA-signed certificate and bind it via an SSL/TLS service profile instead of using the default self-signed cert.' },
  { id: 'FW-ADM-007', category: 'Administrative Access', title: 'No external authentication profile (RADIUS/LDAP/SAML) configured', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 1.8', 'NIST SP 800-41 §4.2'], test: function (t) { const m = /set shared authentication-profile|set shared server-profile (radius|ldap|saml)/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Integrate admin authentication with a centralized identity provider (RADIUS/LDAP/SAML) rather than local accounts only.' },
  { id: 'FW-NET-001', category: 'Network Hardening', title: 'SNMP v1/v2c in use', severity: 'high', standards: ['CIS Palo Alto Networks Benchmark 4.1'], test: function (t) { const m = findLines(t, /snmp[^\n]*version[^\n]*(v1|v2c)/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Migrate SNMP polling to v3 with authentication (SHA) and privacy (AES) enabled.' },
  { id: 'FW-NET-002', category: 'Network Hardening', title: 'Zone protection profile not applied', severity: 'manual', standards: ['CIS Palo Alto Networks Benchmark 3.3'], test: function () { return makeResult(this, 'manual', []); }, remediation: 'Verify each security zone has a zone-protection profile applied to mitigate flood, reconnaissance and packet-based attacks.' },
  { id: 'FW-NET-003', category: 'Network Hardening', title: 'DoS protection profile not referenced', severity: 'manual', standards: ['CIS Palo Alto Networks Benchmark 3.6'], test: function (t) { const m = /dos-protection-profile/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Apply DoS protection profiles/rules to critical zones to bound per-source and aggregate session/connection rates.' },
  { id: 'FW-CONT-001', category: 'Content Security', title: 'Security rules missing threat-prevention (vulnerability) profile', severity: 'high', standards: ['CIS Palo Alto Networks Benchmark 2.1'], test: function (t) { const m = /set profiles vulnerability|set rulebase security rules[^\n]*profile-setting[^\n]*vulnerability/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach a Vulnerability Protection profile to all allow rules carrying traffic from lower-trust to higher-trust zones.' },
  { id: 'FW-CONT-002', category: 'Content Security', title: 'Security rules missing antivirus profile', severity: 'high', standards: ['CIS Palo Alto Networks Benchmark 2.2'], test: function (t) { const m = /set profiles virus|profile-setting[^\n]*virus/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach an Antivirus profile to allow rules so file transfers are inspected for known malware signatures.' },
  { id: 'FW-CONT-003', category: 'Content Security', title: 'Security rules missing URL filtering profile', severity: 'medium', standards: ['CIS Palo Alto Networks Benchmark 2.3'], test: function (t) { const m = /set profiles url-filtering|profile-setting[^\n]*url-filtering/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach a URL Filtering profile to outbound rules to block known-malicious and policy-violating categories.' },
  { id: 'FW-CONT-004', category: 'Content Security', title: 'File blocking profile not applied', severity: 'low', standards: ['CIS Palo Alto Networks Benchmark 2.4'], test: function (t) { const m = /set profiles file-blocking/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Apply a File Blocking profile to restrict high-risk file types (e.g. executables) traversing the firewall.' },
  { id: 'FW-MON-001', category: 'Logging & Monitoring', title: 'No log-forwarding profile referenced', severity: 'medium', standards: ['NIST SP 800-41 §4.5', 'PCI-DSS 10.5'], test: function (t) { const m = /log-setting/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach a log-forwarding profile to security rules and forward traffic/threat logs to a SIEM.' },
  { id: 'FW-TIME-001', category: 'Time Synchronization', title: 'NTP servers not configured', severity: 'low', standards: ['NIST SP 800-41 §4.5', 'PCI-DSS 10.4'], test: function (t) { const m = findLines(t, /set deviceconfig system ntp-servers/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Configure primary and secondary NTP servers under "set deviceconfig system ntp-servers".' },
];

const fortinetRules = [
  { id: 'FW-ACC-001', category: 'Access Control', title: 'Firewall policy allows all-to-all traffic', severity: 'critical', standards: ['CIS Fortinet FortiOS Benchmark 3.1', 'PCI-DSS 1.2.1'], test: function (t) { const blocks = t.split(/(?=config firewall policy)/i); const hits = []; for (const b of blocks) { if (/set srcaddr\s+"?all"?/i.test(b) && /set dstaddr\s+"?all"?/i.test(b) && /set action\s+accept/i.test(b)) { const first = b.split(/\r?\n/).slice(0, 4).join(' | ').trim(); hits.push(first); } } return hits.length ? makeResult(this, 'fail', hits) : makeResult(this, 'pass'); }, remediation: 'Scope srcaddr/dstaddr to specific address objects and services rather than "all"; rely on default-deny.' },
  { id: 'FW-ACC-002', category: 'Access Control', title: 'Firewall policies missing logging directive', severity: 'manual', standards: ['CIS Fortinet FortiOS Benchmark 3.6'], test: function () { return makeResult(this, 'manual', []); }, remediation: 'Confirm "set logtraffic all" (or utm) is present on every policy carrying production traffic.' },
  { id: 'FW-ACC-003', category: 'Access Control', title: 'Policies not using NAT/interface-based least privilege review', severity: 'manual', standards: ['CIS Fortinet FortiOS Benchmark 3.7'], test: function () { return makeResult(this, 'manual', []); }, remediation: 'Review policies for unused or overly broad interface bindings (any-any zone pairs) during periodic rule review.' },
  { id: 'FW-ADM-001', category: 'Administrative Access', title: 'Telnet allowed on an administrative interface', severity: 'critical', standards: ['CIS Fortinet FortiOS Benchmark 1.1', 'PCI-DSS 2.3'], test: function (t) { const m = findLines(t, /set allowaccess[^\n]*telnet/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Remove telnet from "set allowaccess"; use HTTPS and SSH only for administrative interfaces.' },
  { id: 'FW-ADM-002', category: 'Administrative Access', title: 'HTTP (non-TLS) admin access allowed', severity: 'high', standards: ['CIS Fortinet FortiOS Benchmark 1.2'], test: function (t) { const m = findLines(t, /set allowaccess[^\n]*\bhttp\b(?!s)/i); return m.length ? makeResult(this, 'fail', m) : makeResult(this, 'pass'); }, remediation: 'Remove "http" from allowaccess, keeping only "https" for the GUI and "ssh" for CLI.' },
  { id: 'FW-ADM-003', category: 'Administrative Access', title: 'Admin idle timeout not restricted', severity: 'medium', standards: ['CIS Fortinet FortiOS Benchmark 1.3'], test: function (t) { const m = findLines(t, /set admintimeout\s+\d+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Set "set admintimeout <=15" minutes under config system accprofile / global settings.' },
  { id: 'FW-ADM-004', category: 'Administrative Access', title: 'Password policy not enforced', severity: 'medium', standards: ['CIS Fortinet FortiOS Benchmark 1.4', 'PCI-DSS 8.2.3'], test: function (t) { const m = /config system password-policy/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable "config system password-policy" with minimum length and complexity requirements for local accounts.' },
  { id: 'FW-ADM-005', category: 'Administrative Access', title: 'Pre-login / post-login banner not configured', severity: 'low', standards: ['CIS Fortinet FortiOS Benchmark 1.5'], test: function (t) { const m = /set pre-login-banner enable|set post-login-banner enable/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable pre-login and post-login banners ("set pre-login-banner enable") to display an authorized-use warning.' },
  { id: 'FW-ADM-006', category: 'Administrative Access', title: 'Default admin trusted hosts not restricted', severity: 'medium', standards: ['CIS Fortinet FortiOS Benchmark 1.6'], test: function (t) { const m = findLines(t, /set trusthost\d?\s+\S+/i); return m.length ? makeResult(this, 'pass', m) : makeResult(this, 'fail', []); }, remediation: 'Restrict administrator accounts to specific management-network trusted hosts via "set trusthost1/2/3".' },
  { id: 'FW-ADM-007', category: 'Administrative Access', title: 'Central management / FortiGuard connectivity not configured', severity: 'low', standards: ['CIS Fortinet FortiOS Benchmark 4.4'], test: function (t) { const m = /config system central-management|config system fortiguard/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Configure FortiGuard/central management so signature, firmware and reputation feeds stay current.' },
  { id: 'FW-NET-001', category: 'Network Hardening', title: 'SNMP v1/v2c community configured', severity: 'high', standards: ['CIS Fortinet FortiOS Benchmark 4.1'], test: function (t) { const m = /config system snmp-community/i.test(t); return m ? makeResult(this, 'fail', findLines(t, /config system snmp-community|set query-v1-status enable|set query-v2c-status enable/i)) : makeResult(this, 'pass'); }, remediation: 'Disable SNMP v1/v2c communities and migrate to "config system snmp-user" (SNMPv3) with auth and privacy.' },
  { id: 'FW-NET-002', category: 'Network Hardening', title: 'Default/factory TLS certificate in use on admin GUI', severity: 'medium', standards: ['CIS Fortinet FortiOS Benchmark 1.7'], test: function (t) { const m = /set admin-server-cert/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Install a CA-signed certificate and bind it via "set admin-server-cert" instead of the default Fortinet_Factory cert.' },
  { id: 'FW-NET-003', category: 'Network Hardening', title: 'High-Availability heartbeat authentication not configured', severity: 'manual', standards: ['CIS Fortinet FortiOS Benchmark 5.1'], test: function (t) { const m = /config system ha/i.test(t); return m ? makeResult(this, 'manual') : makeResult(this, 'manual'); }, remediation: 'If HA is deployed, confirm "set ha-mgmt-status" and HA password/authentication are configured to prevent cluster hijacking.' },
  { id: 'FW-CONT-001', category: 'Content Security', title: 'Firewall policies missing antivirus profile', severity: 'high', standards: ['CIS Fortinet FortiOS Benchmark 2.1'], test: function (t) { const m = /set av-profile/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach an AV profile ("set av-profile") to policies carrying file transfers, especially internet-facing traffic.' },
  { id: 'FW-CONT-002', category: 'Content Security', title: 'Firewall policies missing IPS profile', severity: 'high', standards: ['CIS Fortinet FortiOS Benchmark 2.2'], test: function (t) { const m = /set ips-sensor/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach an IPS sensor ("set ips-sensor") to policies to detect and block known exploit patterns.' },
  { id: 'FW-CONT-003', category: 'Content Security', title: 'Firewall policies missing web filter profile', severity: 'medium', standards: ['CIS Fortinet FortiOS Benchmark 2.3'], test: function (t) { const m = /set webfilter-profile/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Attach a web filter profile to outbound policies to block malicious/policy-violating categories.' },
  { id: 'FW-CONT-004', category: 'Content Security', title: 'Application control profile not applied', severity: 'low', standards: ['CIS Fortinet FortiOS Benchmark 2.4'], test: function (t) { const m = /set application-list/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'manual'); }, remediation: 'Apply an application-control profile to gain visibility and control over traffic by application, not just port.' },
  { id: 'FW-MON-001', category: 'Logging & Monitoring', title: 'No log settings block found', severity: 'medium', standards: ['NIST SP 800-41 §4.5', 'PCI-DSS 10.5'], test: function (t) { const m = /config log /i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Configure "config log syslogd setting" (or FortiAnalyzer) and enable logging on all policies.' },
  { id: 'FW-TIME-001', category: 'Time Synchronization', title: 'NTP not configured', severity: 'low', standards: ['NIST SP 800-41 §4.5', 'PCI-DSS 10.4'], test: function (t) { const m = /config system ntp/i.test(t); return m ? makeResult(this, 'pass') : makeResult(this, 'fail', []); }, remediation: 'Enable "config system ntp" with at least two trusted time sources.' },
];

const awsRules = [
  { id: 'CIS-AWS-1.4', category: 'Identity and Access Management', title: 'Ensure MFA is enabled for all IAM users with a console password', severity: 'critical', standards: ['CIS AWS Foundations v2.0.0 §1.4', 'PCI-DSS v4.0 §8.4.2'], test: function (t) { if (/"password_enabled":\s*true/i.test(t) && !/"mfa_active":\s*true/i.test(t)) { return makeResult(this, 'fail', ['Violation: Account configuration reveals credential profile active without active MFA structures.']); } return makeResult(this, 'pass'); }, remediation: 'Enforce Multi-Factor Authentication via IAM policies for all user profiles initialized with infrastructure access routing privileges.' },
  { id: 'CIS-AWS-1.5', category: 'Identity and Access Management', title: 'Ensure MFA is enabled for the Root User account', severity: 'critical', standards: ['CIS AWS Foundations v2.0.0 §1.5', 'NIST SP 800-53 IA-2'], test: function (t) { const rootMfa = findLines(t, /"root_account_mfa_enabled":\s*false/i); return rootMfa.length ? makeResult(this, 'fail', rootMfa) : makeResult(this, 'pass'); }, remediation: 'Log into the AWS Console using root authority assets and activate an hardware or virtual MFA container immediately.' },
  { id: 'CIS-AWS-1.14', category: 'Identity and Access Management', title: 'Ensure Access Keys are rotated every 90 days or fewer', severity: 'high', standards: ['CIS AWS Foundations v2.0.0 §1.14'], test: function (t) { const expiredKeys = findLines(t, /"access_key_age_days":\s*(9[1-9]|\d{3,})/i); return expiredKeys.length ? makeResult(this, 'fail', expiredKeys) : makeResult(this, 'pass'); }, remediation: 'Decommission persistent credentials exceeding standard rotation parameters. Implement short-lived credentials through IAM Roles instead.' },
  { id: 'CIS-AWS-2.1.1', category: 'Storage and S3 Hardening', title: 'Ensure S3 Buckets have Block Public Access configuration enabled', severity: 'critical', standards: ['CIS AWS Foundations v2.0.0 §2.1.1', 'ISO 27001:2022 A.8.24'], test: function (t) { const publicBuckets = findLines(t, /"BlockPublicAcls":\s*false|"IgnorePublicAcls":\s*false/i); return publicBuckets.length ? makeResult(this, 'fail', publicBuckets) : makeResult(this, 'pass'); }, remediation: 'Modify S3 Public Access options to explicitly block all ACL and Bucket policy permissions at the structural tier level.' },
  { id: 'CIS-AWS-3.1', category: 'Logging & Central Monitoring', title: 'Ensure CloudTrail is configured across all infrastructure regions', severity: 'high', standards: ['CIS AWS Foundations v2.0.0 §3.1', 'PCI-DSS v4.0 §10.2.1'], test: function (t) { if (t.trim().length > 0 && !/"IsMultiRegionTrail":\s*true/i.test(t)) { return makeResult(this, 'fail', ['Multi-region logging visibility flag absent or false within tracking parameter.']); } return makeResult(this, 'pass'); }, remediation: 'Enable global structural configuration options inside CloudTrail deployment settings to register multi-region operational data.' },
  { id: 'CIS-AWS-5.1', category: 'VPC Networking Architecture', title: 'Ensure no Security Groups allow ingress mapping from 0.0.0.0/0 to port 22', severity: 'critical', standards: ['CIS AWS Foundations v2.0.0 §5.1', 'NIST SP 800-41 §4.3'], test: function (t) { const openSsh = findLines(t, /"FromPort":\s*22.*"CidrIp":\s*"0\.0\.0\.0\/0"/i) || /cidr_blocks\s*=\s*\[\s*"0\.0\.0\.0\/0"\s*\].*port\s*=\s*22/i.test(t); return openSsh ? makeResult(this, 'fail', ['Unrestricted management interfaces detected open to structural perimeter limits.']) : makeResult(this, 'pass'); }, remediation: 'Isolate access routes. Transition standard terminal connectivity from internet paths into secure boundary tunnels (e.g., AWS Systems Manager Session Manager).' },
];

[ciscoRules, paloaltoRules, fortinetRules, awsRules].forEach(set => { set.forEach(r => { r.test = r.test.bind(r); }); });

const VENDOR_RULES = { cisco: ciscoRules, paloalto: paloaltoRules, fortinet: fortinetRules, aws: awsRules };

function detectVendor(text) {
  const awsScore = (text.match(/"MfaActive"|"BlockPublicAcls"|"IsMultiRegionTrail"|aws:iam|"password_enabled"/gi) || []).length;
  const ciscoScore = (text.match(/ASA Version|line vty|interface GigabitEthernet|ip access-list|hostname \S+/gi) || []).length;
  const paScore = (text.match(/set rulebase|set deviceconfig|set network interface|from-zone|to-zone/gi) || []).length;
  const fortiScore = (text.match(/config firewall|config system|set allowaccess|next\s*\n\s*end/gi) || []).length;
  const scores = { aws: awsScore, cisco: ciscoScore, paloalto: paScore, fortinet: fortiScore };
  let best = 'aws', bestScore = -1;
  for (const k in scores) { if (scores[k] > bestScore) { bestScore = scores[k]; best = k; } }
  if (bestScore === 0) return null;
  return best;
}

function assessFirewallConfig(configText, vendorOverride) {
  const text = configText.trim();
  let vendor = vendorOverride;
  if (!vendor || vendor === 'auto') { vendor = detectVendor(text) || 'cisco'; }
  const rules = VENDOR_RULES[vendor] || ciscoRules;
  const findings = rules.map(r => r.test(text));

  const counts = { critical: 0, high: 0, medium: 0, low: 0, pass: 0, manual: 0 };
  findings.forEach(f => counts[f.severity]++);
  const scoreable = findings.filter(f => f.severity !== 'manual');
  const pct = scoreable.length ? Math.round(100 * counts.pass / scoreable.length) : 0;

  return {
    vendor,
    totalControls: findings.length,
    complianceScore: pct,
    counts,
    findings,
  };
}

module.exports = { assessFirewallConfig, detectVendor, VENDOR_RULES };
